services:
  - type: web
    name: interviewbuddy
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      # Set these in Render Dashboard with your real values or override here
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: ALLOW_ALL_ORIGINS
        value: "false"
    healthCheckPath: /health
